# Exploração inicial dos dados

In [1]:
import pandas as pd
from pathlib import Path
import os

from src.models.demonstracoes_contabeis import DemonstracoesContabeis

In [2]:
data = DemonstracoesContabeis()
data.get_anos_disponiveis()
data.get_demonstracoes_contabeis()
data.save_demonstracoes_contabeis()

2025

## Lendo csv

In [3]:
file = "1T2025.csv"
df = pd.read_csv(f"{Path(os.getcwd()).resolve().parent}/data/raw/demonstracoes_contabeis/{file}",
      sep=";",
      encoding="latin-1",
      decimal=",")
df.head()

,DATA,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL
0,2025-01-01,316458,46411,PUBLICIDADE E PROPAGANDA,0.0,1070.00
1,2025-01-01,316458,464119,Publicidade e Propaganda,0.0,1070.00
2,2025-01-01,316458,46411901,Publicidade e Propaganda,0.0,1070.00
3,2025-01-01,316458,464119011,Publicidade e Propaganda,0.0,1070.00
4,2025-01-01,316458,465,DESPESAS COM TRIBUTOS,0.0,99024.72

In [4]:
BASE_URL_CADOP = "https://dadosabertos.ans.gov.br/FTP/PDA/operadoras_de_plano_de_saude_ativas/Relatorio_cadop.csv"
BASE_URL_CADOP_CANCELADAS = "https://dadosabertos.ans.gov.br/FTP/PDA/operadoras_de_plano_de_saude_canceladas/Relatorio_cadop_canceladas.csv"

In [5]:
df_cadop_cancelados = pd.read_csv(BASE_URL_CADOP_CANCELADAS,
      sep=";", 
      encoding="latin-1",
      decimal=",")
df_cadop_cancelados.head()

,REGISTRO_OPERADORA,CNPJ,Razao_Social,Nome_Fantasia,Modalidade,Logradouro,Numero,Complemento,Bairro,Cidade,...,DDD,Telefone,Fax,Endereco_eletronico,Representante,Cargo_Representante,Regiao_de_Comercializacao,Data_Registro_ANS,Data_Descredenciamento,Motivo_do_Descredenciamento
0,410942,3607971000192,24 HORAS SISTEMA DE SAUDE S/C LTDA,24 HORAS,Medicina de Grupo,RUA PROPICIA,187,NaN,ENGENHO NOVO,Rio de Janeiro,...,21,25010935,25010935,saude24-horas@ig.com.br,MARCOS ANTONIO GARCIA PEREIRA,SOCIO GERENTE,NaN,2000-03-23,2003-12-19,Pedido de cancelamento
1,422908,41788751000100,3S ADMINISTRADORA DE BENEFICIOS LTDA,3S ADMINISTRADORA DE BENEFICIOS,Administradora de BenefÃ­cios,RUA ITÃLIA,33,SALA 6,JARDIM BONFIGLIOLI,JundiaÃ­,...,11,42263247,NaN,pietrorocchi37@gmail.com,ANAMELIA MONTEIRO GUERRA ROCCHI,SÃCIO ADMINISTRADOR,6.0,2021-07-12,2025-07-21,BAIXA DE INSCRIÃÃO NO CNPJ
2,419575,18108766000150,A LA SANTE ADMINISTRADORA DE BENEFICIO LTDA.,A LA SANTE,Administradora de BenefÃ­cios,RUA OLIMPIADAS,205,4Âº ANDAR,VILA OLIMPIA,SÃ£o Paulo,...,11,36833438,NaN,NaN,LARISSA DIAS DA SILVA,SOCIA ADMINISTRADORA,4.0,2014-10-06,2017-10-10,DeliberaÃ§Ã£o de Diretoria Colegiada
3,320439,50928563000112,A M P ASSISTENCIA MEDICA PAULISTA S/C LTDA,A M P ASSISTENCIA MEDICA PAULISTA S/C LTDA,Medicina de Grupo,RUA CAV. ERNESTO GIULIANO,979,NaN,OLIMPICO,SÃ£o Caetano do Sul,...,11,26354,26354,NaN,MOYSES FRIEDHEIM,DIRETOR TESOUREIRO,NaN,1999-01-27,2000-12-13,Pedido de cancelamento
4,406821,3246912000136,A ORAL OESTE'S ASSISTENCIA EM ODONTOLOGIA S/C ...,A ORAL OESTE'S ASSISTENCIA EM ODONTOLOGIA S/C ...,Odontologia de Grupo,RUA: BRIGADEIRO GAVIÃO PEIXOTO,132,NaN,LAPA,SÃ£o Paulo,...,11,8330140,NaN,NaN,ANGELA RUGGIERO,NaN,NaN,1999-08-03,2003-05-29,AusÃªncia de operaÃ§Ã£o - DeliberaÃ§Ã£o de Dir...

In [6]:
df_cadop = pd.read_csv(BASE_URL_CADOP,
      sep=";",
      encoding="latin-1",
      decimal=",")
df_cadop.head()

,REGISTRO_OPERADORA,CNPJ,Razao_Social,Nome_Fantasia,Modalidade,Logradouro,Numero,Complemento,Bairro,Cidade,UF,CEP,DDD,Telefone,Fax,Endereco_eletronico,Representante,Cargo_Representante,Regiao_de_Comercializacao,Data_Registro_ANS
0,419761,19541931000125,18 DE JULHO ADMINISTRADORA DE BENEFÃCIOS LTDA,NaN,Administradora de BenefÃ­cios,RUA CAPITÃO MEDEIROS DE REZENDE,274,NaN,PRAÃA DA BANDEIRA,AlÃ©m ParaÃ­ba,MG,36660000,32.0,34624649.0,NaN,contabilidade@cbnassessoria.com.br,LUIZ HENRIQUE MARENDINO GONÃALVES,SÃCIO ADMINISTRADOR,6.0,2015-05-19
1,421545,22869997000153,2B ODONTOLOGIA OPERADORA DE PLANOS ODONTOLÃGI...,NaN,Odontologia de Grupo,RUA CATÃO,128,SALA 126,VILA ROMANA,SÃ£o Paulo,SP,5049000,11.0,34415852.0,NaN,labmarisol@gmail.com,MARISOL BECHELLI,SÃCIO ADMINISTRADORA,4.0,2019-06-13
2,421421,27452545000195,2CARE OPERADORA DE SAÃDE LTDA.,NaN,Medicina de Grupo,RUA: BERNARDINO DE CAMPOS,230,1Âº ANDAR,CENTRO,Campinas,SP,13010151,19.0,37901224.0,NaN,ans.plano@hospitalcare.com.br,RODRIGO PINHO RIBEIRO,REPRESENTANTE,5.0,2018-10-09
3,418030,13138885000131,A.P.S. ADMINISTRADORA DE BENEFÃCOS LTDA.,A.P.S. SAÃDE.,Administradora de BenefÃ­cios,RUA VOLUNTÃRIOS DA PÃTRIA,2525,CONJUNTO 143 - SALA 01,SANTANA,SÃ£o Paulo,SP,2401000,11.0,45223468.0,NaN,diretoria@apssaude.com.br,PERCÃVEL GAETA,SÃ³CIO-ADMINISTRADOR E REPRESEN,4.0,2011-05-05
4,314668,17505793000101,ABERTTA SAÃDE - ASSOCIAÃÃO BENEFICENTE DOS ...,ABERTTA SAÃDE,AutogestÃ£o,AV. BERNARDO MONTEIRO,831,"Subsolo, 2Âº andar e 3Âº andar",SANTA EFIGÃNIA,Belo Horizonte,MG,30150281,31.0,32484300.0,32484377.0,abertta.ans@arcelormittal.com.br,WERNER DUARTE DALLA,Diretor Presidente,4.0,1998-12-28

## Analise exploratoria dos dados

In [7]:
df_cadop_cancelados.info()

<class 'pandas.DataFrame'>
RangeIndex: 3046 entries, 0 to 3045
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   REGISTRO_OPERADORA           3046 non-null   int64
 1   CNPJ                         3046 non-null   int64
 2   Razao_Social                 3046 non-null   str
 3   Nome_Fantasia                2591 non-null   str
 4   Modalidade                   3046 non-null   str
 5   Logradouro                   3044 non-null   str
 6   Numero                       3003 non-null   str
 7   Complemento                  1314 non-null   str
 8   Bairro                       3038 non-null   str
 9   Cidade                       3046 non-null   str
 10  UF                           3046 non-null   str
 11  CEP                          3045 non-null   float64
 12  DDD                          2985 non-null   str
 13  Telefone                     3003 non-null   str
 14  Fax                          2395 non-null   str
 15  Endereco_eletronico          2513 non-null   str
 16  Representante                2855 non-null   str
 17  Cargo_Representante          2719 non-null   str
 18  Regiao_de_Comercializacao    1427 non-null   float64
 19  Data_Registro_ANS            3046 non-null   str
 20  Data_Descredenciamento       3046 non-null   str
 21  Motivo_do_Descredenciamento  3046 non-null   str
dtypes: float64(2), int64(2), str(18)
memory usage: 523.7 KB

In [8]:
df_cadop_cancelados.CNPJ.value_counts()

CNPJ
8543312000153     2
6258813000162     2
94093085000143    2
76106483000175    2
60586450000130    2
                 ..
1382881000115     1
62568084000111    1
39330166000101    1
10311779000110    1
4492825000121     1
Name: count, Length: 3007, dtype: int64

In [9]:
lista_cnpjs = [94093085000143, 8543312000153, 76106483000175]
df_cadop_cancelados.loc[df_cadop_cancelados.CNPJ.isin(lista_cnpjs) ]

,REGISTRO_OPERADORA,CNPJ,Razao_Social,Nome_Fantasia,Modalidade,Logradouro,Numero,Complemento,Bairro,Cidade,...,DDD,Telefone,Fax,Endereco_eletronico,Representante,Cargo_Representante,Regiao_de_Comercializacao,Data_Registro_ANS,Data_Descredenciamento,Motivo_do_Descredenciamento
35,419036,8543312000153,ADMISA ASSISTENCIA ODONTOLOGICA LTDA,NaN,Odontologia de Grupo,RUA DOUTOR QUIRINO,734,3Âº ANDAR - SALA 34,CENTRO,Campinas,...,19,31122900,NaN,WALTER@ASSIMEDICA.COM.BR,WALTER ROSA FILHO,SÃ³CIO-ADMINISTRADOR,6.0,2013-09-11,2015-05-14,Descumprimento de disposiÃ§Ã£o legal
36,418471,8543312000153,ADMISA ASSISTÃNCIA ODONTOLÃGICA LTDA,ADMISA ASSISTÃNCIA ODONTOLÃGICA LTDA,Odontologia de Grupo,RUA DOUTOR QUIRINO,734,NaN,CENTRO,Campinas,...,19,31122900,31122900,WALTER@ASSIMEDICA.COM.BR,WALTER ROSA FILHO,ADMINISTRADOR,NaN,2012-03-26,2013-05-06,Descumprimento de disposiÃ§Ã£o legal
82,414671,94093085000143,AMA - ASSISTÃNCIA MÃDICA ADMINISTRADA S/S LTDA.,AMA,Administradora,RUA GOMES JARDIM,472,NaN,SANTANA,Porto Alegre,...,51,32173434,32173434,juridico@amars.com.br,GUSTAVO LORENZONI SPORLEDER,DIRETOR COMERCIAL,4.0,2003-10-10,2010-05-18,Pedido de cancelamento
84,389862,94093085000143,AMA ASSISTENCIA MÃDICA ADMINISTRADA LTDA.,NaN,Administradora,",",472,NaN,SANTANA,Porto Alegre,...,51,2170465,2171402,ama@ez-poa.com.br,FERNANDO ADERBAL CABELERA SPORLEDER,SÃCIO,NaN,1998-12-30,2000-12-27,Pedido de cancelamento
174,412872,76106483000175,ASSOCIACAO PARANAENSE DO MINISTERIO PUBLICO,APMP,AutogestÃ£o,RUA MATEUS LEME,2018,NaN,CENTRO CIVICO,Curitiba,...,41,33242829,33522855,promed@apmppr.org.br,CLAUDIO FRANCO FELIX,PRESIDENTE,3.0,2000-12-21,2017-11-03,Pedido de cancelamento
190,35298,76106483000175,ASSOCIAÃAO PARANAENSE DO MINISTÃRIO PUBLICO,PROMED,AutogestÃ£o,AV.CANDIDO DE ABREU,526,10 ANDAR- TORRE A,CENTRO CIVICO,Curitiba,...,41,3522855,2541240,apmp@fast.com.br,SONNY MARTINS CARNEIRO,X,NaN,1999-01-06,1999-09-20,Descumprimento da Circular SUSEP no. 77/1999

Consigo notar que os casos de repeticao dos cnpjs que acontecem estao associados a cancelamentos distintos

In [10]:
df_cadop.CNPJ.value_counts()

CNPJ
19541931000125    1
22869997000153    1
27452545000195    1
13138885000131    1
17505793000101    1
                 ..
58014237000101    1
14927215000167    1
2811372000123     1
28023703000154    1
33379144000150    1
Name: count, Length: 1110, dtype: int64

In [11]:
df_cadop.loc[df_cadop.REGISTRO_OPERADORA == 316458] # faco so um teste para ver se eu encontro esse valor da lista de demonstracoes contabeis nos registros

,REGISTRO_OPERADORA,CNPJ,Razao_Social,Nome_Fantasia,Modalidade,Logradouro,Numero,Complemento,Bairro,Cidade,UF,CEP,DDD,Telefone,Fax,Endereco_eletronico,Representante,Cargo_Representante,Regiao_de_Comercializacao,Data_Registro_ANS
924,316458,41511429000120,UNIMED REGIONAL DE FLORIANO - COOPERATIVA DE T...,UNIMED FLORIANO,Cooperativa MÃ©dica,AV EURIPEDES DE AGUIAR,943,NaN,CENTRO,Floriano,PI,64800000,89.0,35211133.0,35216652.0,financeiro@unimedfloriano.com.br,SALOMÃO VICENTE AIRES JÃNIOR,PRESIDENTE,5.0,1998-12-21

Podemos ver que para esse caso não temos CNPJs duplicados

In [12]:
df_cadop_concat = pd.concat([df_cadop, df_cadop_cancelados], ignore_index=True)
df_cadop.REGISTRO_OPERADORA.value_counts()

REGISTRO_OPERADORA
419761    1
421545    1
421421    1
418030    1
314668    1
         ..
424315    1
419354    1
400882    1
407534    1
421944    1
Name: count, Length: 1110, dtype: int64

Continuasmos com nenhum registro de operadora repedito

In [13]:
cols = ["REGISTRO_OPERADORA", "CNPJ", "Razao_Social"]
df_reg_ans = df_cadop_concat[cols]

df_reg_ans = df_reg_ans.rename(columns={
    'REGISTRO_OPERADORA': 'REG_ANS'
})

In [14]:
df_reg_ans.head()

   REG_ANS            CNPJ                                       Razao_Social
0   419761  19541931000125     18 DE JULHO ADMINISTRADORA DE BENEFÃCIOS LTDA
1   421545  22869997000153  2B ODONTOLOGIA OPERADORA DE PLANOS ODONTOLÃGI...
2   421421  27452545000195                    2CARE OPERADORA DE SAÃDE LTDA.
3   418030  13138885000131          A.P.S. ADMINISTRADORA DE BENEFÃCOS LTDA.
4   314668  17505793000101  ABERTTA SAÃDE - ASSOCIAÃÃO BENEFICENTE DOS ...

In [15]:
df_reg_ans.loc[df_reg_ans.REG_ANS == 27]

      REG_ANS           CNPJ                                    Razao_Social
2727       27  4518814000173  MASSA FALIDA DE SALUTAR SAÃDE SEGURADORA S.A.

esse valor tava muito estranho fui testar kkkk