In [1]:
import pandas as pd
from pathlib import Path
import os

from src.models.demonstracoes_contabeis import DemonstracoesContabeis

In [2]:
data = DemonstracoesContabeis()
data.get_anos_disponiveis()
data.get_demonstracoes_contabeis()
data.save_demonstracoes_contabeis()
df_reg_ans = data.get_relatorios_cadop()
df_reg_ans.head()

,REG_ANS,CNPJ,Razao_Social,Nome_Fantasia,Modalidade,Logradouro,Numero,Complemento,Bairro,Cidade,...,Telefone,Fax,Endereco_eletronico,Representante,Cargo_Representante,Regiao_de_Comercializacao,Data_Registro_ANS,Data_Descredenciamento,Motivo_do_Descredenciamento,RegASNAtivo
0,410942,3607971000192,24 HORAS SISTEMA DE SAUDE S/C LTDA,24 HORAS,Medicina de Grupo,RUA PROPICIA,187,NaN,ENGENHO NOVO,Rio de Janeiro,...,25010935,25010935,saude24-horas@ig.com.br,MARCOS ANTONIO GARCIA PEREIRA,SOCIO GERENTE,NaN,2000-03-23,2003-12-19,Pedido de cancelamento,True
1,422908,41788751000100,3S ADMINISTRADORA DE BENEFICIOS LTDA,3S ADMINISTRADORA DE BENEFICIOS,Administradora de BenefÃ­cios,RUA ITÃLIA,33,SALA 6,JARDIM BONFIGLIOLI,JundiaÃ­,...,42263247,NaN,pietrorocchi37@gmail.com,ANAMELIA MONTEIRO GUERRA ROCCHI,SÃCIO ADMINISTRADOR,6.0,2021-07-12,2025-07-21,BAIXA DE INSCRIÃÃO NO CNPJ,True
2,419575,18108766000150,A LA SANTE ADMINISTRADORA DE BENEFICIO LTDA.,A LA SANTE,Administradora de BenefÃ­cios,RUA OLIMPIADAS,205,4Âº ANDAR,VILA OLIMPIA,SÃ£o Paulo,...,36833438,NaN,NaN,LARISSA DIAS DA SILVA,SOCIA ADMINISTRADORA,4.0,2014-10-06,2017-10-10,DeliberaÃ§Ã£o de Diretoria Colegiada,True
3,320439,50928563000112,A M P ASSISTENCIA MEDICA PAULISTA S/C LTDA,A M P ASSISTENCIA MEDICA PAULISTA S/C LTDA,Medicina de Grupo,RUA CAV. ERNESTO GIULIANO,979,NaN,OLIMPICO,SÃ£o Caetano do Sul,...,26354,26354,NaN,MOYSES FRIEDHEIM,DIRETOR TESOUREIRO,NaN,1999-01-27,2000-12-13,Pedido de cancelamento,True
4,406821,3246912000136,A ORAL OESTE'S ASSISTENCIA EM ODONTOLOGIA S/C ...,A ORAL OESTE'S ASSISTENCIA EM ODONTOLOGIA S/C ...,Odontologia de Grupo,RUA: BRIGADEIRO GAVIÃO PEIXOTO,132,NaN,LAPA,SÃ£o Paulo,...,8330140,NaN,NaN,ANGELA RUGGIERO,NaN,NaN,1999-08-03,2003-05-29,AusÃªncia de operaÃ§Ã£o - DeliberaÃ§Ã£o de Dir...,True

In [3]:
file = "1T2025.csv"
df_1T = pd.read_csv(f"{Path(os.getcwd()).resolve().parent}/data/raw/demonstracoes_contabeis/{file}",
      sep=";",           
      encoding="latin-1",
      decimal=",")
df_1T.head()

,DATA,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL
0,2025-01-01,316458,46411,PUBLICIDADE E PROPAGANDA,0.0,1070.00
1,2025-01-01,316458,464119,Publicidade e Propaganda,0.0,1070.00
2,2025-01-01,316458,46411901,Publicidade e Propaganda,0.0,1070.00
3,2025-01-01,316458,464119011,Publicidade e Propaganda,0.0,1070.00
4,2025-01-01,316458,465,DESPESAS COM TRIBUTOS,0.0,99024.72

In [4]:
file_2 = "2T2025.csv"
df_2T = pd.read_csv(f"{Path(os.getcwd()).resolve().parent}/data/raw/demonstracoes_contabeis/{file_2}",
      sep=";",           
      encoding="latin-1",
      decimal=",")
df_2T.head()

,DATA,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL
0,2025-04-01,421723,452119014,Juros - PESL,0.0,0.0
1,2025-04-01,421723,452119015,VariaÃ§Ã£o cambial - PESL,0.0,0.0
2,2025-04-01,421723,452119019,Outras,0.0,0.0
3,2025-04-01,421723,45212,DESPESAS FINANCEIRAS COM OPERAÃÃES DE ASSIST...,0.0,0.0
4,2025-04-01,421723,452129,Despesas Financeiras com OperaÃ§Ãµes de Assist...,0.0,0.0

In [5]:
file_3 = "3T2025.csv"
df_3T = pd.read_csv(f"{Path(os.getcwd()).resolve().parent}/data/raw/demonstracoes_contabeis/{file_2}",
      sep=";",           
      encoding="latin-1",
      decimal=",")
df_3T.head()

,DATA,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL
0,2025-04-01,421723,452119014,Juros - PESL,0.0,0.0
1,2025-04-01,421723,452119015,VariaÃ§Ã£o cambial - PESL,0.0,0.0
2,2025-04-01,421723,452119019,Outras,0.0,0.0
3,2025-04-01,421723,45212,DESPESAS FINANCEIRAS COM OPERAÃÃES DE ASSIST...,0.0,0.0
4,2025-04-01,421723,452129,Despesas Financeiras com OperaÃ§Ãµes de Assist...,0.0,0.0

In [6]:
df_concat = pd.concat([df_1T, df_2T, df_3T], ignore_index=True)

## Analise dos casos de REG_ANS ausentes

In [7]:
df_filrado_com_cnpj = df_concat.merge(df_reg_ans, how="inner", on="REG_ANS", indicator=True)
df_sem_correspondencia = df_filrado_com_cnpj[df_filrado_com_cnpj['_merge'] == 'left_only']
df_sem_correspondencia.head()

Empty DataFrame
Columns: [DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL, CNPJ, Razao_Social, Nome_Fantasia, Modalidade, Logradouro, Numero, Complemento, Bairro, Cidade, UF, CEP, DDD, Telefone, Fax, Endereco_eletronico, Representante, Cargo_Representante, Regiao_de_Comercializacao, Data_Registro_ANS, Data_Descredenciamento, Motivo_do_Descredenciamento, RegASNAtivo, _merge]
Index: []

[0 rows x 29 columns]

Não há nenhum caso onde os dados de REGANS não estejam incluídos! Tendo em vista que eu fiz a junção com os cancelados, nesse caso eu consigo os dados de forma mais completa e ainda com as informações importantes