In [4]:
import pandas as pd
from pathlib import Path
import os

from src.main import main

In [5]:
df = main()
df.head()

,REG_ANS,CNPJ,RazaoSocial,Trimestre,Ano,ValorDespesas,Modalidade,UF,CnpjValido,ValorValido,RazaoSocialValida,RegASNAtivo
0,316849,42465310000121,TELOS - FUNDAÃÃO EMBRATEL DE SEGURIDADE SOCIAL,1T2025,2025,3558.06,AutogestÃ£o,RJ,True,True,True,False
1,316849,42465310000121,TELOS - FUNDAÃÃO EMBRATEL DE SEGURIDADE SOCIAL,1T2025,2025,0.00,AutogestÃ£o,RJ,True,True,True,False
2,316849,42465310000121,TELOS - FUNDAÃÃO EMBRATEL DE SEGURIDADE SOCIAL,1T2025,2025,-3300.99,AutogestÃ£o,RJ,True,False,True,False
3,316849,42465310000121,TELOS - FUNDAÃÃO EMBRATEL DE SEGURIDADE SOCIAL,1T2025,2025,-3300.99,AutogestÃ£o,RJ,True,False,True,False
4,316903,93507895000136,POLIMÃDICA SAÃDE SOCIEDADE SIMPLES LTDA,1T2025,2025,0.00,Medicina de Grupo,RS,True,True,True,False

## Total por Razao_Social

In [6]:
df_razao_social = df.groupby('RazaoSocial')['ValorDespesas'].sum()
df_razao_social.head()

RazaoSocial
2CARE OPERADORA DE SAÃDE LTDA.                                                        9.433195e+08
A.P.S. ADMINISTRADORA DE BENEFÃCOS LTDA.                                             -3.048900e+02
ABERTTA SAÃDE - ASSOCIAÃÃO BENEFICENTE DOS EMPREGADOS DA ARCELORMITTAL NO BRASIL    8.089483e+08
ADVANCE PLANOS DE SAÃDE LTDA                                                          1.099024e+08
AESP ODONTO ASSISTÃNCIA ODONTOLÃGICA S/S LTDA EPP                                    1.891737e+07
Name: ValorDespesas, dtype: float64

## Total por UF

In [7]:
df_uf = df.groupby('UF')['ValorDespesas'].sum()
df_uf.head()

UF
AC    7.649623e+08
AL    4.877425e+09
AM    2.353464e+09
AP    1.780654e+07
BA    5.287422e+09
Name: ValorDespesas, dtype: float64

# Medias

## Operadora

In [8]:
df_operadora = df.groupby('CNPJ').agg({
    'ValorDespesas': ['sum', 'mean', 'count', 'std'],
    'RazaoSocial': 'first'
})

df_operadora.head()

             ValorDespesas                                    \
                       sum          mean count           std
CNPJ
6037000127    3.605046e+08  1.574256e+06   229  4.274398e+06
12698000165   8.217715e+07  3.260998e+05   252  8.537118e+05
34259000153   9.922752e+07  1.181280e+06    84  2.485821e+06
103956000119  4.577124e+08  1.486079e+06   308  4.532105e+06
111826000128  6.173339e+08  2.173711e+06   284  6.017333e+06

                                                    RazaoSocial
                                                          first
CNPJ
6037000127    UNIMED DE TATUI - COOPERATIVA DE TRABALHO MÃDICO
12698000165   UNIMED DE PENAPOLIS - COOPERATIVA DE TRABALHO ...
34259000153   ASSOCIAÃÃO POLICIAL DE ASSISTÃNCIA A SAÃDE...
103956000119  UNIMED LITORAL SUL/RS - COOPERATIVA DE ASSISTÃ...
111826000128  UNIMED ARARUAMA COOPERATIVA DE TRABALHO MÃDIC...

In [9]:
df_uf_trimestre = df.groupby(['UF', 'Trimestre'])['ValorDespesas'].mean().reset_index()
df_uf_trimestre.columns = ['UF', 'Trimestre', 'MediaDespesas']
df_uf_trimestre = df_uf_trimestre.sort_values(by='MediaDespesas')
df_uf_trimestre.head()

    UF Trimestre  MediaDespesas
9   AP    1T2025  340592.130000
10  AP    2T2025  378088.933125
11  AP    3T2025  394227.449375
77  TO    3T2025  996950.982019
76  TO    2T2025  999898.575500